[package]
name = "ckb-rocksdb"
description = "Rust wrapper for Facebook's RocksDB embeddable database"
version = "1.0.0"
edition = "2024"
authors = ["Tyler Neely <t@jujit.su>", "David Greenberg <dsg123456789@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
license = "Apache-2.0"
keywords = ["database", "embedded", "LSM-tree", "persistence"]
repository = "https://github.com/nervosnetwork/ckb-rocksdb"
readme = "README.md"
documentation = "https://docs.rs/ckb-rocksdb"
categories = ["database"]
include = ["src/**", "tests/**", "benches/**", "LICENSE", "README.md", "CHANGELOG.md"]
rust-version = "1.95.0"

[workspace]
members = ["librocksdb-sys"]
resolver = "3"

[features]
default = ["snappy", "lz4", "zstd", "zlib", "bzip2"]
valgrind = []
snappy = ["librocksdb-sys/snappy"]
lz4 = ["librocksdb-sys/lz4"]
zstd = ["librocksdb-sys/zstd"]
zlib = ["librocksdb-sys/zlib"]
bzip2 = ["librocksdb-sys/bzip2"]
jemalloc = ["librocksdb-sys/jemalloc"]
io-uring = ["librocksdb-sys/io-uring"]
portable = ["librocksdb-sys/portable"]
march-native = ["librocksdb-sys/march-native"]
serde1 = ["serde"]
lto = ["librocksdb-sys/lto"]
rtti = ["librocksdb-sys/rtti"]

[dependencies]
libc = "0.2.189"
librocksdb-sys = { package = "ckb-librocksdb-sys", path = "librocksdb-sys", version = "=11.8.1" }
tempfile = "3.27.0"
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
trybuild = "1.0.121"
criterion = "0.8.2"

[[bench]]
name = "transaction"
harness = false
